FROM python:3.11-slim

# Arbeitsverzeichnis im Container
WORKDIR /app

# Abhängigkeiten kopieren und installieren
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Applikationscode kopieren
COPY src ./src

# Port (nur Dokumentation, optional)
EXPOSE 8000

# Startbefehl
CMD ["uvicorn", "src.api.api:app", "--host", "0.0.0.0", "--port", "8000"]